package org.basic.net.c20_jmx.mbean.simple;

//
// Generated by proxygen version 5.1 when compiling SimpleStandard (Tue Apr 13 19:21:58 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;


/**
 * The proxy MBean interface of the SimpleStandard MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface SimpleStandardProxyMBean {

  public java.lang.String getState()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.Integer getNbChanges()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setState(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void reset()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
