
//
// Generated by proxygen version 5.1 when compiling com.sun.jdmk.cascading.CascadingAgent (Tue Apr 13 19:26:06 MEST 2004).
//

package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;


import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import javax.management.QueryExp;
import com.sun.jdmk.comm.ConnectorAddress;
import java.util.Set;
import javax.management.ObjectName;


/**
 * The proxy MBean interface of the CascadingAgent MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface CascadingAgentProxyMBean {

  public javax.management.QueryExp getQuery()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public com.sun.jdmk.comm.ConnectorAddress getAddress()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getClientConnectorClassName()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.Integer getNbOfRemoteMBeans()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.util.Set getRemoteMBeans()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public javax.management.ObjectName getPattern()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setAddress(com.sun.jdmk.comm.ConnectorAddress value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setClientConnectorClassName(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
