package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;

//
// Generated by proxygen version 5.1 when compiling CounterMonitor (Tue Apr 13 19:27:14 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import javax.management.ObjectName;
import javax.management.Attribute;
import javax.management.ObjectInstance;
import com.sun.jdmk.comm.CommunicationException;
import com.sun.jdmk.comm.RemoteMBeanServer;
import com.sun.jdmk.ProxyHandler;
import javax.management.NotificationListener;
import javax.management.NotificationFilter;
import javax.management.ListenerNotFoundException;


/**
 * The implementation of the CounterMonitorProxyMBean Proxy MBean interface.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public class CounterMonitorProxy implements CounterMonitorProxyMBean, com.sun.jdmk.Proxy, com.sun.jdmk.NotificationBroadcasterProxy {

  //
  // granularity for allocating new array
  //
  private int _granularity= 10;


  //
  // Variables required by Proxy interface
  //
  protected ObjectInstance objectInstance = null;
  protected ProxyHandler server = null;


  /**
   *  constructor with ObjectInstance parameter
   */
  public CounterMonitorProxy(ObjectInstance oi) {    
    objectInstance = oi ;
  }

  /**
   *  constructor with ObjectInstance parameter and ProxyHandler server
   */
  public CounterMonitorProxy(ObjectInstance oi, ProxyHandler server) {    
    objectInstance = oi ;
    this.server = server ;
  }

  public java.lang.Number getOffset()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Number)server.getAttribute(objectInstance.getObjectName(), "Offset"));
    }

  public java.lang.Number getDerivedGauge()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Number)server.getAttribute(objectInstance.getObjectName(), "DerivedGauge"));
    }

  public long getDerivedGaugeTimeStamp()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Long)server.getAttribute(objectInstance.getObjectName(), "DerivedGaugeTimeStamp")).longValue());
    }

  public java.lang.Number getThreshold()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Number)server.getAttribute(objectInstance.getObjectName(), "Threshold"));
    }

  public java.lang.Number getInitThreshold()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Number)server.getAttribute(objectInstance.getObjectName(), "InitThreshold"));
    }

  public java.lang.Number getModulus()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Number)server.getAttribute(objectInstance.getObjectName(), "Modulus"));
    }

  public boolean getNotify()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Boolean)server.getAttribute(objectInstance.getObjectName(), "Notify")).booleanValue());
    }

  public boolean getDifferenceMode()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Boolean)server.getAttribute(objectInstance.getObjectName(), "DifferenceMode")).booleanValue());
    }

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Boolean)server.getAttribute(objectInstance.getObjectName(), "Active")).booleanValue());
    }

  public long getGranularityPeriod()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Long)server.getAttribute(objectInstance.getObjectName(), "GranularityPeriod")).longValue());
    }

  public java.lang.String getObservedAttribute()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.String)server.getAttribute(objectInstance.getObjectName(), "ObservedAttribute"));
    }

  public javax.management.ObjectName getObservedObject()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((javax.management.ObjectName)server.getAttribute(objectInstance.getObjectName(), "ObservedObject"));
    }

  public ObjectName[] getObservedObjects()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((ObjectName[])server.getAttribute(objectInstance.getObjectName(), "ObservedObjects"));
    }

  public  void setOffset(java.lang.Number value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("Offset",value));
  }

  public  void setThreshold(java.lang.Number value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("Threshold",value));
  }

  public  void setInitThreshold(java.lang.Number value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("InitThreshold",value));
  }

  public  void setModulus(java.lang.Number value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("Modulus",value));
  }

  public  void setNotify(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("Notify",new Boolean(value)));
  }

  public  void setDifferenceMode(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("DifferenceMode",new Boolean(value)));
  }

  public  void setGranularityPeriod(long value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("GranularityPeriod",new Long(value)));
  }

  public  void setObservedAttribute(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("ObservedAttribute",value));
  }

  public  void setObservedObject(javax.management.ObjectName value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("ObservedObject",value));
  }

  public java.lang.Number getDerivedGauge(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "getDerivedGauge", params, signature);
    return ((java.lang.Number) result);
  }

  public long getDerivedGaugeTimeStamp(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "getDerivedGaugeTimeStamp", params, signature);
    return ((Long) result).longValue();
  }

  public java.lang.Number getThreshold(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "getThreshold", params, signature);
    return ((java.lang.Number) result);
  }

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    result= server.invoke(objectInstance.getObjectName(), "start", null, null);
  }

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    result= server.invoke(objectInstance.getObjectName(), "stop", null, null);
  }

  public void addObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "addObservedObject", params, signature);
  }

  public void removeObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "removeObservedObject", params, signature);
  }

  public boolean containsObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[1];
    String[] signature= new String[1];

    params[0]= p0;
    signature[0]= "javax.management.ObjectName";

    result= server.invoke(objectInstance.getObjectName(), "containsObservedObject", params, signature);
    return ((Boolean) result).booleanValue();
  }

  //
  // Implementation of NotificationBroadcasterProxy interface
  //
  public synchronized  void addNotificationListener(ObjectName name, NotificationListener listener, NotificationFilter filter, Object handback)
    throws InstanceNotFoundException {

    server.addNotificationListener(objectInstance.getObjectName(), listener, filter, handback);
  }

  public synchronized  void removeNotificationListener(ObjectName name, NotificationListener listener)
    throws InstanceNotFoundException, ListenerNotFoundException {

    server.removeNotificationListener(objectInstance.getObjectName(), listener);
  }

  //
  // Implementation of the Proxy interface
  //

  /**
   *  Returns the <a href="javax.management.ObjectInstance.html#_top_"> object instance</a> of the object
   */
  public ObjectInstance getMBeanObjectInstance()  {
    return (objectInstance);
  }

  public ProxyHandler getServer() {
    return server;
  }

  public void setServer(ProxyHandler server) {
    this.server = server;
  }


}
