
//
// Generated by proxygen version 5.1 when compiling com.sun.jdmk.discovery.DiscoveryClient (Tue Apr 13 19:28:06 MEST 2004).
//

package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;


import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import java.util.Vector;


/**
 * The proxy MBean interface of the DiscoveryClient MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface DiscoveryClientProxyMBean {

  public java.lang.Integer getState()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getMulticastGroup()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getMulticastPort()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getTimeOut()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getTimeToLive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getPointToPointResponse()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getStateString()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setMulticastGroup(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setMulticastPort(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setTimeOut(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setTimeToLive(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setPointToPointResponse(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Vector findMBeanServers(java.lang.String p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Vector findMBeanServers()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Vector findCommunicators(java.lang.String p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Vector findCommunicators()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
