
//
// Generated by proxygen version 5.1 when compiling com.sun.jdmk.discovery.DiscoveryResponder (Tue Apr 13 19:28:49 MEST 2004).
//

package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;


import javax.management.Attribute;
import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.ObjectInstance;
import javax.management.ReflectionException;

import com.sun.jdmk.ProxyHandler;


/**
 * The implementation of the DiscoveryResponderProxyMBean Proxy MBean interface.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public class DiscoveryResponderProxy implements DiscoveryResponderProxyMBean, com.sun.jdmk.Proxy {

  //
  // granularity for allocating new array
  //
  private int _granularity= 10;


  //
  // Variables required by Proxy interface
  //
  protected ObjectInstance objectInstance = null;
  protected ProxyHandler server = null;

  /**
   *  constructor with ObjectInstance parameter
   */
  public DiscoveryResponderProxy(ObjectInstance oi) {    
    objectInstance = oi ;
  }

  /**
   *  constructor with ObjectInstance parameter and ProxyHandler server
   */
  public DiscoveryResponderProxy(ObjectInstance oi, ProxyHandler server) {    
    objectInstance = oi ;
    this.server = server ;
  }

  public java.lang.Integer getState()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.Integer)server.getAttribute(objectInstance.getObjectName(), "State"));
    }

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Boolean)server.getAttribute(objectInstance.getObjectName(), "Active")).booleanValue());
    }

  public java.lang.String getMulticastGroup()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.String)server.getAttribute(objectInstance.getObjectName(), "MulticastGroup"));
    }

  public int getMulticastPort()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Integer)server.getAttribute(objectInstance.getObjectName(), "MulticastPort")).intValue());
    }

  public int getTimeToLive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return (((Integer)server.getAttribute(objectInstance.getObjectName(), "TimeToLive")).intValue());
    }

  public java.lang.String getStateString()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((java.lang.String)server.getAttribute(objectInstance.getObjectName(), "StateString"));
    }

  public byte[] getUserData()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException {

      return ((byte[])server.getAttribute(objectInstance.getObjectName(), "UserData"));
    }

  public  void setMulticastGroup(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("MulticastGroup",value));
  }

  public  void setMulticastPort(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("MulticastPort",new Integer(value)));
  }

  public  void setTimeToLive(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("TimeToLive",new Integer(value)));
  }

  public  void setUserData(byte[] value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException {

      server.setAttribute(objectInstance.getObjectName(), new Attribute("UserData",value));
  }

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    result= server.invoke(objectInstance.getObjectName(), "start", null, null);
  }

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    result= server.invoke(objectInstance.getObjectName(), "stop", null, null);
  }

  public boolean waitState(int p0, long p1)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException {

    Object result;
    Object[] params= new Object[2];
    String[] signature= new String[2];

    params[0]= new Integer(p0);
    signature[0]= "int";
    params[1]= new Long(p1);
    signature[1]= "long";

    result= server.invoke(objectInstance.getObjectName(), "waitState", params, signature);
    return ((Boolean) result).booleanValue();
  }

  //
  // Implementation of the Proxy interface
  //

  /**
   *  Returns the <a href="javax.management.ObjectInstance.html#_top_"> object instance</a> of the object
   */
  public ObjectInstance getMBeanObjectInstance()  {
    return (objectInstance);
  }

  public ProxyHandler getServer() {
    return server;
  }

  public void setServer(ProxyHandler server) {
    this.server = server;
  }


}
