
//
// Generated by proxygen version 5.1 when compiling com.sun.jdmk.discovery.DiscoveryMonitor (Tue Apr 13 19:28:22 MEST 2004).
//

package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;


import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;


/**
 * The proxy MBean interface of the DiscoveryMonitor MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface DiscoveryMonitorProxyMBean {

  public java.lang.Integer getState()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getStateString()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getMulticastGroup()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getMulticastPort()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setMulticastGroup(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setMulticastPort(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public boolean waitState(int p0, long p1)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
