package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;

//
// Generated by proxygen version 5.1 when compiling GaugeMonitor (Tue Apr 13 19:27:34 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import javax.management.ObjectName;


/**
 * The proxy MBean interface of the GaugeMonitor MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface GaugeMonitorProxyMBean {

  public java.lang.Number getDerivedGauge()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public long getDerivedGaugeTimeStamp()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.Number getHighThreshold()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.Number getLowThreshold()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getNotifyHigh()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getNotifyLow()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getDifferenceMode()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public long getGranularityPeriod()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getObservedAttribute()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public javax.management.ObjectName getObservedObject()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public ObjectName[] getObservedObjects()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setNotifyHigh(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setNotifyLow(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setDifferenceMode(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setGranularityPeriod(long value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setObservedAttribute(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setObservedObject(javax.management.ObjectName value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public java.lang.Number getDerivedGauge(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public long getDerivedGaugeTimeStamp(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void setThresholds(java.lang.Number p0, java.lang.Number p1)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void addObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void removeObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public boolean containsObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
