package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;

//
// Generated by proxygen version 5.1 when compiling MBeanServerDelegate (Tue Apr 13 19:31:17 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;


/**
 * The proxy MBean interface of the MBeanServerDelegate MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface MBeanServerDelegateProxyMBean {

  public java.lang.String getImplementationVendor()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getImplementationVersion()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getSpecificationVendor()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getSpecificationVersion()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getMBeanServerId()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getSpecificationName()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getImplementationName()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;


}
