
//
// Generated by proxygen version 5.1 when compiling com.sun.jdmk.comm.RmiConnectorServer (Tue Apr 13 19:29:32 MEST 2004).
//

package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;


import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;


/**
 * The proxy MBean interface of the RmiConnectorServer MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface RmiConnectorServerProxyMBean {

  public java.lang.String getServiceName()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getState()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getHost()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getProtocol()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getStateString()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getPort()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setServiceName(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setPort(int value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public boolean waitState(int p0, long p1)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
