package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;

//
// Generated by proxygen version 5.1 when compiling StringMonitor (Tue Apr 13 19:27:46 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import javax.management.ObjectName;


/**
 * The proxy MBean interface of the StringMonitor MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface StringMonitorProxyMBean {

  public java.lang.String getDerivedGauge()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public long getDerivedGaugeTimeStamp()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getStringToCompare()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getNotifyMatch()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getNotifyDiffer()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public long getGranularityPeriod()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.lang.String getObservedAttribute()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public javax.management.ObjectName getObservedObject()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public ObjectName[] getObservedObjects()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setStringToCompare(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setNotifyMatch(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setNotifyDiffer(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setGranularityPeriod(long value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setObservedAttribute(java.lang.String value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public  void setObservedObject(javax.management.ObjectName value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public java.lang.String getDerivedGauge(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public long getDerivedGaugeTimeStamp(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void addObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void removeObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public boolean containsObservedObject(javax.management.ObjectName p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
