package org.basic.net.c20_jmx.jdmk.legacy.JdmkProxyMBeans;

//
// Generated by proxygen version 5.1 when compiling Timer (Tue Apr 13 19:31:00 MEST 2004).
//

import javax.management.AttributeNotFoundException;
import javax.management.InstanceNotFoundException;
import javax.management.InvalidAttributeValueException;
import javax.management.MBeanException;
import javax.management.MBeanRegistrationException;
import javax.management.ReflectionException;
import java.util.Vector;
import java.util.Date;


/**
 * The proxy MBean interface of the Timer MBean.
 *
 * @see com.sun.jdmk.tools.ProxyGen 
 */
public interface TimerProxyMBean {

  public boolean isEmpty()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean isActive()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public int getNbNotifications()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public java.util.Vector getAllNotificationIDs()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public boolean getSendPastNotifications()
    throws InstanceNotFoundException, AttributeNotFoundException,
    ReflectionException, MBeanException;

  public  void setSendPastNotifications(boolean value)
    throws InstanceNotFoundException, ReflectionException,
    AttributeNotFoundException,InvalidAttributeValueException,
    MBeanException;

  public void start()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void stop()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Date getDate(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Integer addNotification(java.lang.String p0, java.lang.String p1, java.lang.Object p2, java.util.Date p3, long p4, long p5)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Integer addNotification(java.lang.String p0, java.lang.String p1, java.lang.Object p2, java.util.Date p3, long p4)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Integer addNotification(java.lang.String p0, java.lang.String p1, java.lang.Object p2, java.util.Date p3)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Integer addNotification(java.lang.String p0, java.lang.String p1, java.lang.Object p2, java.util.Date p3, long p4, long p5, boolean p6)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void removeNotification(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void removeNotifications(java.lang.String p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public void removeAllNotifications()
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.util.Vector getNotificationIDs(java.lang.String p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.String getNotificationType(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.String getNotificationMessage(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Object getNotificationUserData(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Long getPeriod(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Long getNbOccurences(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;

  public java.lang.Boolean getFixedRate(java.lang.Integer p0)
    throws InstanceNotFoundException, ReflectionException,
    MBeanException;


}
