CREATE TABLE PRODUCT (
  ID INTEGER NOT NULL identity,
  NAME VARCHAR(20),
  PRICE DECIMAL(10,2),
  VERSION INTEGER DEFAULT 0,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT SYS_PK_PRODUCT PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10098_10099 ON PRODUCT (ID);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (0,'Iron Clock',3.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (1,'Ice Tea Iron',21.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (2,'Telephone Shoe',12.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (3,'Telephone Telephone',13.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (4,'Telephone Clock',23.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (5,'Clock Chair',21.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (6,'Telephone Ice Tea',15.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (7,'Chair Clock',24.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (8,'Shoe Iron',13.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (9,'Clock Ice Tea',22.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (10,'Chair Iron',16.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (11,'Ice Tea Shoe',13.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (12,'Ice Tea Chair',25.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (13,'Iron Telephone',25.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (14,'Shoe Clock',10.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (15,'Telephone Chair',14.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (16,'Telephone Shoe',19.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (17,'Clock Clock',13.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (18,'Telephone Chair',2.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (19,'Chair Iron',5.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (20,'Chair Ice Tea',16.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (21,'Telephone Shoe',14.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (22,'Shoe Ice Tea',6.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (23,'Shoe Iron',7.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (24,'Telephone Ice Tea',22.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (25,'Clock Shoe',21.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (26,'Iron Chair',17.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (27,'Clock Shoe',19.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (28,'Chair Shoe',23.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (29,'Iron Clock',14.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (30,'Ice Tea Clock',5.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (31,'Clock Clock',10.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (32,'Iron Clock',4.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (33,'Clock Clock',14.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (34,'Chair Iron',16.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (35,'Iron Telephone',23.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (36,'Chair Telephone',20.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (37,'Chair Iron',8.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (38,'Chair Ice Tea',22.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (39,'Telephone Telephone',6.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (40,'Shoe Shoe',5.20);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (41,'Shoe Telephone',19.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (42,'Shoe Iron',10.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (43,'Iron Chair',21.80);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (44,'Telephone Iron',19.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (45,'Iron Iron',2.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (46,'Clock Telephone',6.40);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (47,'Iron Clock',5.00);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (48,'Iron Clock',6.60);
INSERT INTO PRODUCT (ID,NAME,PRICE) VALUES (49,'Telephone Chair',2.00);
