CREATE table dm_person (
  id INTEGER  identity,
  name VARCHAR(64),
  first_name VARCHAR(64),
  last_name VARCHAR(64),
  sex char(1) DEFAULT 'F',
  "AGE" DECIMAL(5,0),  
  "PROFESSION" VARCHAR(20) DEFAULT 'WORKER' NOT NULL, 
  "POSITION" VARCHAR(32) DEFAULT 'Manager', 
  "EMBLEMENT" VARCHAR(32) DEFAULT 'WHEAT',
  VERSION INTEGER DEFAULT 0,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT CRT_DM_PERSON_PK PRIMARY KEY (ID)
);
ALTER TABLE dm_person ADD CONSTRAINT dm_person_CHK_AGE CHECK (AGE BETWEEN 0 AND 100);
ALTER TABLE dm_person ADD CONSTRAINT dm_person_UK_NAME UNIQUE (FIRST_NAME, LAST_NAME);

--CREATE UNIQUE INDEX IDX_USER_PK ON User(ID);
INSERT INTO dm_person(ID, NAME, first_name, last_name, AGE, VERSION, MODIFIED_DATE, CREATED_DATE)
   VALUES(1, 'Angela', 'Angela', 'Yang', 33, 0, '2020-01-02 21:03:01.871', '2020-01-02 21:03:01.871');
