package org.basic.grammar.jdk.jdk7.e5_networking.ws.client.doc_encoded_bare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServicePort", targetNamespace = "http://www.wstest.org/hello")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePort {


    /**
     * 
     * @param listUser
     * @return
     *     returns org.basic.jdk6.ws.client.doc_encoded_bare.UserArray
     */
    @WebMethod
    @WebResult(name = "listUserResponse", targetNamespace = "http://www.wstest.org/hello", partName = "listUserResponse")
    @Action(input = "http://www.wstest.org/hello/HelloServicePort/listUserRequest", output = "http://www.wstest.org/hello/HelloServicePort/listUserResponse")
    public UserArray listUser(
        @WebParam(name = "listUser", targetNamespace = "http://www.wstest.org/hello", partName = "listUser")
        String listUser);

}
