
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.third.cxf.service.book;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-06-09T15:51:44.654+08:00
 * Generated source version: 2.7.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "BookService",
                      portName = "BookServicePort_HttpGet",
                      targetNamespace = "http://service.cxf.third.org/Book/",
                      wsdlLocation = "http://localhost:9002/cxf/BookServiceSoapRpcLiteralImpl?wsdl",
                      endpointInterface = "org.third.cxf.service.book.IBookService")
                      
public class IBookServiceImpl3 implements IBookService {

    private static final Logger LOG = Logger.getLogger(IBookServiceImpl3.class.getName());

    /* (non-Javadoc)
     * @see org.third.cxf.service.book.IBookService#getBookByName(java.lang.String  bookName )*
     */
    public org.third.cxf.service.book.BookType getBookByName(java.lang.String bookName) { 
        LOG.info("Executing operation getBookByName");
        System.out.println(bookName);
        try {
            org.third.cxf.service.book.BookType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
