package org.basic.net.c16_corba.hello.hellostub;

/**
* org/basic/corba/hello/hellostub/FileServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public final class FileServerHolder implements org.omg.CORBA.portable.Streamable
{
  public org.basic.net.c16_corba.hello.hellostub.FileServer value = null;

  public FileServerHolder ()
  {
  }

  public FileServerHolder (org.basic.net.c16_corba.hello.hellostub.FileServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.basic.net.c16_corba.hello.hellostub.FileServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.basic.net.c16_corba.hello.hellostub.FileServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.basic.net.c16_corba.hello.hellostub.FileServerHelper.type ();
  }

}
