package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/FileServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public final class FileServer implements org.omg.CORBA.portable.IDLEntity
{
  public int port = (int)0;
  public org.omg.CORBA.Any value = null;

  public FileServer ()
  {
  } // ctor

  public FileServer (int _port, org.omg.CORBA.Any _value)
  {
    port = _port;
    value = _value;
  } // ctor

} // class FileServer
