package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/InternalException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public final class InternalException extends org.omg.CORBA.UserException
{
  public short errorCode = (short)0;
  public String reason = null;
  public boolean otherMsg = false;

  public InternalException ()
  {
    super(InternalExceptionHelper.id());
  } // ctor

  public InternalException (short _errorCode, String _reason, boolean _otherMsg)
  {
    super(InternalExceptionHelper.id());
    errorCode = _errorCode;
    reason = _reason;
    otherMsg = _otherMsg;
  } // ctor


  public InternalException (String $reason, short _errorCode, String _reason, boolean _otherMsg)
  {
    super(InternalExceptionHelper.id() + "  " + $reason);
    errorCode = _errorCode;
    reason = _reason;
    otherMsg = _otherMsg;
  } // ctor

} // class InternalException
