package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/InternalExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

abstract public class InternalExceptionHelper
{
  private static String  _id = "IDL:org/basic/corba/hello/hellostub/InternalException:1.0";

  public static void insert (org.omg.CORBA.Any a, org.basic.net.c16_corba.hello.hellostub.InternalException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.basic.net.c16_corba.hello.hellostub.InternalException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _members0[0] = new org.omg.CORBA.StructMember (
            "errorCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "reason",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "otherMsg",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (org.basic.net.c16_corba.hello.hellostub.InternalExceptionHelper.id (), "InternalException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.basic.net.c16_corba.hello.hellostub.InternalException read (org.omg.CORBA.portable.InputStream istream)
  {
    org.basic.net.c16_corba.hello.hellostub.InternalException value = new org.basic.net.c16_corba.hello.hellostub.InternalException ();
    // read and discard the repository ID
    istream.read_string ();
    value.errorCode = istream.read_ushort ();
    value.reason = istream.read_string ();
    value.otherMsg = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.basic.net.c16_corba.hello.hellostub.InternalException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_ushort (value.errorCode);
    ostream.write_string (value.reason);
    ostream.write_boolean (value.otherMsg);
  }

}
