package org.basic.net.c16_corba.hello.hellostub;

/**
* org/basic/corba/hello/hellostub/IntefaceListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/


//`float' `double' `long' `short' `unsigned' `char' `wchar' `boolean' `octet' `any';
public final class IntefaceListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.basic.net.c16_corba.hello.hellostub.IntefaceList value = null;

  public IntefaceListHolder ()
  {
  }

  public IntefaceListHolder (org.basic.net.c16_corba.hello.hellostub.IntefaceList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.basic.net.c16_corba.hello.hellostub.IntefaceListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.basic.net.c16_corba.hello.hellostub.IntefaceListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.basic.net.c16_corba.hello.hellostub.IntefaceListHelper.type ();
  }

}
