package org.third.cxf.service.impl;

import java.util.logging.Logger;

import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;

import org.third.cxf.service.book.BookType;
import org.third.cxf.service.book.IBookService;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2014-03-06T16:33:54.027+08:00
 * Generated source version: 2.7.6
 * 
 */

@javax.jws.WebService(
        
                      serviceName = "BookService",
                      portName = "BookServicePort_SoapDocumentLiteral",
                      targetNamespace = "http://service.cxf.third.org/Book/",
                      endpointInterface = "org.third.cxf.service.book.IBookService")

@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE, use=Use.ENCODED)
public class BookServiceSoapDocumentLiteralImpl implements IBookService {

    private static final Logger LOG = Logger.getLogger(BookServiceHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see org.third.cxf.service.book.IBookService#getBookByName(java.lang.String  bookName )*
     */
    public org.third.cxf.service.book.BookType getBookByName(java.lang.String bookName) { 
        LOG.info("Executing operation getBookByName");
        System.out.println(bookName);
        try {
            org.third.cxf.service.book.BookType _return = new BookType();
            _return.setBookId(102303l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
