
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-06-09T15:51:44.660+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://service.cxf.third.org/Book/", name = "IBookService")
@XmlSeeAlso({ObjectFactory.class})
public interface IBookService {

    @WebResult(name = "book", targetNamespace = "")
    @RequestWrapper(localName = "getBookByName", targetNamespace = "http://service.cxf.third.org/Book/", className = "org.third.cxf.service.book.GetBookByName")
    @WebMethod(action = "http://service.cxf.third.org/Book/getBookByName")
    @ResponseWrapper(localName = "getBookByNameResponse", targetNamespace = "http://service.cxf.third.org/Book/", className = "org.third.cxf.service.book.GetBookByNameResponse")
    public org.third.cxf.service.book.BookType getBookByName(
        @WebParam(name = "bookName", targetNamespace = "")
        java.lang.String bookName
    );
}
