package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/GoodDay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public interface GoodDay extends GoodDayOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final String NAME_OBJECT = "GoodDayNameObject";
} // interface GoodDay
