package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/TypeSeqStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public final class TypeSeqStringHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public TypeSeqStringHolder ()
  {
  }

  public TypeSeqStringHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.basic.net.c16_corba.hello.hellostub.TypeSeqStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.basic.net.c16_corba.hello.hellostub.TypeSeqStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.basic.net.c16_corba.hello.hellostub.TypeSeqStringHelper.type ();
  }

}
