package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/FileServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

abstract public class FileServerHelper
{
  private static String  _id = "IDL:org/basic/corba/hello/hellostub/FileServer:1.0";

  public static void insert (org.omg.CORBA.Any a, org.basic.net.c16_corba.hello.hellostub.FileServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.basic.net.c16_corba.hello.hellostub.FileServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.basic.net.c16_corba.hello.hellostub.TypeDefLongHelper.id (), "TypeDefLong", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "port",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _members0[1] = new org.omg.CORBA.StructMember (
            "value",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.basic.net.c16_corba.hello.hellostub.FileServerHelper.id (), "FileServer", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.basic.net.c16_corba.hello.hellostub.FileServer read (org.omg.CORBA.portable.InputStream istream)
  {
    org.basic.net.c16_corba.hello.hellostub.FileServer value = new org.basic.net.c16_corba.hello.hellostub.FileServer ();
    value.port = istream.read_long ();
    value.value = istream.read_any ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.basic.net.c16_corba.hello.hellostub.FileServer value)
  {
    ostream.write_long (value.port);
    ostream.write_any (value.value);
  }

}
