package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/GoodDayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public interface GoodDayOperations 
{
  String helloSimple ();

  //float balance ();
  String helloWide (String msg);
  String helloWideException (String msg) throws org.basic.net.c16_corba.hello.hellostub.InternalException;
  void lock ();
  boolean ping (String hello);
} // interface GoodDayOperations
