package org.basic.net.c16_corba.hello.hellostub;


/**
* org/basic/corba/hello/hellostub/IntefaceList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/


//`float' `double' `long' `short' `unsigned' `char' `wchar' `boolean' `octet' `any';
public class IntefaceList implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 1;
  private static org.basic.net.c16_corba.hello.hellostub.IntefaceList[] __array = new org.basic.net.c16_corba.hello.hellostub.IntefaceList [__size];

  public static final int _GoodDayIntf = 0;
  public static final org.basic.net.c16_corba.hello.hellostub.IntefaceList GoodDayIntf = new org.basic.net.c16_corba.hello.hellostub.IntefaceList(_GoodDayIntf);

  public int value ()
  {
    return __value;
  }

  public static org.basic.net.c16_corba.hello.hellostub.IntefaceList from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected IntefaceList (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class IntefaceList
