package org.basic.net.c16_corba.hello.hellostub;

/**
* org/basic/corba/hello/hellostub/InternalExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, April 1, 2013 10:51:40 AM CST
*/

public final class InternalExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.basic.net.c16_corba.hello.hellostub.InternalException value = null;

  public InternalExceptionHolder ()
  {
  }

  public InternalExceptionHolder (org.basic.net.c16_corba.hello.hellostub.InternalException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.basic.net.c16_corba.hello.hellostub.InternalExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.basic.net.c16_corba.hello.hellostub.InternalExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.basic.net.c16_corba.hello.hellostub.InternalExceptionHelper.type ();
  }

}
