apiVersion: v1
clusters:
- cluster:
    certificate-authority: /opt/kubernetes/ssl/ca.crt
    server: https://shcemersonvm01.hpeswlab.net:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet-to-kubernetes
current-context: kubelet-to-kubernetes
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    client-certificate: /opt/kubernetes/ssl/kubernetes.crt
    client-key: /opt/kubernetes/ssl/kubernetes.key